export const expenseCategories = [
  "Food & Dining",
  "Groceries",
  "Transportation",
  "Fuel",
  "Rent / Housing",
  "Utilities (Electricity, Water, Internet)",
  "Mobile / Recharge",
  "Healthcare / Medical",
  "Insurance",
  "Education",
  "Shopping",
  "Clothing",
  "Entertainment",
  "Travel",
  "Subscriptions (Netflix, etc.)",
  "Personal Care",
  "Fitness / Gym",
  "Loans / EMI",
  "Investments",
  "Savings",
  "Gifts / Donations",
  "Family Expenses",
  "Pet Care",
  "Miscellaneous"
];